[tools]
"cargo:mergiraf" = "latest"
"cargo:selene" = "latest"
"github:docker/docker-language-server" = "latest"
"github:simonwhitaker/gibo" = "latest"
"github:sqls-server/sqls" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"pipx:neovim-remote" = "latest"
act = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
bun = "latest"
cmake = "latest"
delta = "latest"
deno = "latest"
direnv = "latest"
duckdb = "latest"
eza = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
herdr = "latest"
jq = "latest"
lua-language-server = "latest"
marp-cli = "latest"
mas = "latest"
neovim = "latest"
node = "22.22.0"
postgres = "15"
python = "3.13.5"
ripgrep = "latest"
ruby = "4.0.2"
rust = "latest"
shellcheck = "latest"
tmux = "latest"
tokei = "latest"
tree-sitter = "latest"
uv = "latest"
xcodes = "latest"
yt-dlp = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
