[tools]
"npm:@antfu/ni" = "latest"
"pipx:neovim-remote" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
bun = "latest"
cmake = "latest"
delta = "latest"
deno = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
jq = "latest"
marp-cli = "latest"
neovim = "latest"
node = "22.22.0"
postgres = "15"
python = "3.13.5"
ripgrep = "latest"
ruby = "4.0.2"
rust = "latest"
shellcheck = "latest"
tmux = "latest"
tokei = "latest"
tree-sitter = "latest"
uv = "latest"
yt-dlp = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
