[tools]
node = "latest"
direnv = "2.36.0"
ruby = "4.0.2"
python = "3.11.6"
hub = "2.14.2"
rust = "1.86.0"
deno = "2.7.8"
uv = "0.6.16"
stylua = "latest"
cmake = "latest"
ffmpeg = "latest"
jq = "latest"
tokei = "latest"
yt-dlp = "latest"
delta = "latest"
tmux = "latest"
ripgrep = "latest"
tree-sitter = "0.26.7"
"pipx:neovim-remote" = "latest"
neovim = "latest"
fzf = "latest"
go = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
