i: change_unsafe_mode
esc: change_safe_mode
j: move_down
k: move_up
h: back
l: go
q: quit
Q: quit_without_ask
e: edit
c: cp
m: mv
d: delete_or_trash
D: delete
T: trash
r: rename
K: mkdir
s: sort
w: grep
u: unarchive
p: archive
P: archive_with_password
bb: show_bookmarks
br: register_bookmark
bd: unregister_bookmark
?: help
v: view
C: duplicate
a: select_all
o: open
to: touch
A: invert_selection
gg: move_top
G: move_bottom
ctrl_d: move_down_half_page
ctrl_b: move_up_half_page
ctrl_n: move_up_half_page
ctrl_i: toggle_active_panel
space: toggle_mark
enter: open_or_edit
.: toggle_visible_hidden_entries
L: look
/: find
n: find_repeat
N: find_repeat_reverse
"~": cd_home
;: cd
R: redraw
=: sync_directory
S: shell
tm: "eval system(\"tmux splitw -h '$EDITOR \" + active_panel_controller.current_entry.path + \"'\")"
Y: show_dir_history
H: history_back
yp: copy_path_to_clipboard
yn: copy_filename_to_clipboard
M: mmv
